### ISSUE TITLE
only 4 pieces

### ISSUE THREAD

**Issue by TSTdoll** [myndzi/console-tetris#1]
As of 4d7d909, you need more pieces.

**Comment by myndzi** [comment]
Lol, I know. I wrote this in ~ an hour and a half during an interview process (the focus was getting all the pieces they wanted to see going, not completing data entry). I hosted it so I could show Blitz some things... it's not really intended for use by anyone :)

**Comment by TSTdoll** [comment]
okay

**Comment by TSTdoll** [comment]
Please take it down. You are cluttering the Internet.
